### PR TITLE
Improvment

### PR DESCRIPTION
**Pull request by lifyxus**

### CODE REVIEW

**Comment by xRoier** [comment]
What in the fuck is this PR

**Comment by cookingramen** [comment]
"Improvement" lmao

**Comment by lifyxus** [comment]
image
lol

**Comment by xRoier** [comment]
> image lol

What's wrong

**Comment by xRoier** [comment]
@lifyxus Man, you have 3 repos, of those only 1 is yours and it's a readme repos, so stop being a clown

**Comment by VersLugia** [comment]
🤡🤡🤡

**Comment by moddedmcplayer** [comment]
🤡🤡🤡🤡🤡🤡

**Comment by zhaguanyang** [comment]
🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡

**Pull request closed without merging**
